name: Website Deployment

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Verification
        uses: actions/checkout@v2

      - name: LFTP install
        run: sudo apt-get install -y lftp

      - name: Deployment script execution
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          echo "Script beginning..."
          echo "Connection to $FTP_HOST with username $FTP_USER"
          /usr/bin/lftp -u $FTP_USER,$FTP_PASS $FTP_HOST -e "mirror -R ./ /htdocs/ \
          --exclude .github/ \
          --exclude .git/ \
          --exclude bash/ \
          --exclude assets/images/achievements/ \
          --exclude assets/images/additionnal_items/ \
          --exclude assets/images/artifacts/ \
          --exclude assets/images/books/ \
          --exclude assets/images/bundles/ \
          --exclude assets/images/characters/ \
          --exclude assets/images/cooking_recipes/ \
          --exclude assets/images/crafting_recipes/ \
          --exclude assets/images/dialogue_boxes/ \
          --exclude assets/images/enemies/ \
          --exclude assets/images/farm_animals/ \
          --exclude assets/images/fish/ \
          --exclude assets/images/icons/ \
          --exclude assets/images/minerals/ \
          --exclude assets/images/rewards/ \
          --exclude assets/images/shipped_items/ \
          --exclude assets/images/skills/ \
          --exclude assets/images/social/ \
          --exclude assets/images/steam_achievements/ \
          --exclude assets/images/unlockables/ \
          --exclude styles/less/ \
          --exclude scripts/typescript/ \
          --exclude .gitignore \
          --exclude .htaccess \
          --exclude composer.json \
          --exclude tsconfig.json \
          --exclude package.json \
          --exclude composer.lock \
          --exclude package.lock \
          --exclude README.md; quit"
