name: Website Deployment

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Verification
        uses: actions/checkout@v2

      - name: LFTP install
        run: sudo apt-get install -y lftp

      - name: Create LFTP script
        run: |
          cat > deploy.lftp << EOF
          open -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} ${{ secrets.FTP_HOST }}
          
          # Global settings
          set mirror:use-pget-n 5
          set mirror:parallel-transfer-count 5
          
          # Individual files
          put index.php -o /htdocs/index.php
          put functions.php -o /htdocs/functions.php

          # Mirror specific directories
          mirror -R assets/audio/ /htdocs/assets/audio/
          mirror -R assets/fonts/ /htdocs/assets/fonts/
          mirror -R assets/images/content/ /htdocs/assets/images/content/
          mirror -R assets/images/cursors/ /htdocs/assets/images/cursors/
          mirror -R components/ /htdocs/components/
          mirror -R data/json/ /htdocs/data/json/
          
          # Recursive directories
          mirror -R includes/ /htdocs/includes/
          mirror -R locales/ /htdocs/locales/
          mirror -R scripts/javascript/ /htdocs/scripts/javascript/
          mirror -R styles/css/ /htdocs/styles/css/
          
          # Individual file in subdirectory
          mkdir -f -p /htdocs/data/saves/
          put data/saves/example -o /htdocs/data/saves/example
          
          bye
          EOF

      - name: Deployment script execution
        run: |
          echo "Script beginning..."
          echo "Connection to ${{ secrets.FTP_HOST }} with username ${{ secrets.FTP_USER }}"
          lftp -f deploy.lftp
          echo "Script finished."