name: Website Deployment

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Verification
        uses: actions/checkout@v1

      - name: LFTP install
        run: sudo apt-get install -y lftp

      - name: Create LFTP script
        run: |
          cat > deploy.lftp << EOF
          open -u ${{ secrets.FTP_USER }},${{ secrets.FTP_PASS }} ${{ secrets.FTP_HOST }}
          
          # Global settings
          set mirror:use-pget-n 5
          set mirror:parallel-transfer-count 5
          
          # Individual files
          echo "Transferring individual files..."
          put index.php -o htdocs/index.php
          put functions.php -o htdocs/functions.php
          
          # Individual file in subdirectory
          mkdir -f -p htdocs/data/saves/
          put data/saves/example -o htdocs/data/saves/example
          echo "Transferred individual files successfully."
          
          # Recursive directories
          echo "Transferring directories..."
          mirror -R includes/ htdocs/components/
          mirror -R includes/ htdocs/includes/
          mirror -R locales/ htdocs/locales/
          
          # Mirror specific directories
          mirror -R assets/audio/ htdocs/assets/audio/
          mirror -R assets/fonts/ htdocs/assets/fonts/
          mirror -R assets/images/content/ htdocs/assets/images/content/
          mirror -R assets/images/cursors/ htdocs/assets/images/cursors/
          mirror -R data/json/ htdocs/data/json/
          mirror -R scripts/javascript/ htdocs/scripts/javascript/
          mirror -R styles/css/ htdocs/styles/css/
          echo "Transferred directories successfully."
          
          bye
          EOF

      - name: Deployment script execution
        run: |
          echo "Script beginning..."
          echo -e "\033[1;32mConnected to ${{ secrets.FTP_HOST }} with username ${{ secrets.FTP_USER }}\033[0m"
          lftp -f deploy.lftp
          echo "Script finished."
          