name: Website Deployment

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Code Verification
        uses: actions/checkout@v2

      - name: LFTP install
        run: sudo apt-get install -y lftp

      - name: Deployment script execution
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: |
          echo "Script beginning..."
          echo "Connection to $FTP_HOST with username $FTP_USER"
          /usr/bin/lftp -u $FTP_USER,$FTP_PASS $FTP_HOST -e "mirror -R ./ /htdocs/ \
          --include index.php \
          --include functions.php \
          --include assets/audio/** \
          --include assets/fonts/** \
          --include assets/images/content/** \
          --include assets/images/cursors/** \
          --include assets/images/easter_eggs/** \
          --include components/** \
          --include data/json/** \
          --include data/saves/example \
          --include includes/** \
          --include locales/** \
          --include scripts/javascript/** \
          --include styles/css/** \
          --reverse-include; quit"
          echo "Script finished."
